baseURL = "https://ryananderson.io/"
languageCode = "en-us"
title = "Placeholder Blog"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""
publishDir = "ryananderson.io"

[params]
    author = "Ryan Anderson"
    description = "Personal blog on interesting topics"
    githubUsername = "andersonvc"
    accent = "black"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "python", "rust"]
    copyright = " "


[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4


[[menu.icon]]
    url = "https://github.com/andersonvc/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/bayesianryan/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/andersontech/"
    name = "linkedin"
    weight = 4

